export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_ACCOUNT = 'GET_ACCOUNT';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';
export const LOG_OUT = 'LOG_OUT';
export const STORE_USER_INFO = 'STORE_ACCOUNT';
export const DELETE_USER_INFO = 'DELETE_USER_INFO';
export const DELETE_INFO_SUCCESS = 'DELETE_INFO_SUCCESS';
export const RESTORE_TOKEN = 'RESTORE_TOKEN';

export const TYPE_MY_FIRST_NAME = 'TYPE_MY_FIRST_NAME';
export const TYPE_MY_LAST_NAME = 'TYPE_MY_LAST_NAME';
export const SELECT_MY_GENDER = 'SELECT_MY_GENDER';
export const ON_PRESS_MY_GENDER = 'ON_PRESS_MY_GENDER';
export const SELECT_MY_PHOTO = 'SELECT_MY_PHOTO';

export const TYPE_SPOUSAL_FIRST_NAME = 'TYPE_SPOUSAL_FIRST_NAME';
export const TYPE_SPOUSAL_LAST_NAME = 'TYPE_SPOUSAL_LAST_NAME';
export const ON_PRESS_SPOUSAL_GENDER = 'ON_PRESS_SPOUSAL_GENDER';
export const SELECT_SPOUSAL_GENDER = 'SELECT_SPOUSAL_GENDER';
export const SELECT_SPOUSAL_PHOTO = 'SELECT_SPOUSAL_PHOTO';
