export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const CLASS_SCREEN = 'CLASS_SCREEN';
export const ACCOUNT_SCREEN = 'ACCOUNT_SCREEN';
export const TAB_NAVIGATOR = 'TAB_NAVIGATOR';
export const HOT_TOPIC_SCREEN = 'HOT_TOPIC_SCREEN';
export const PHOTO_ALBUM_SCREEN = 'PHOTO_ALBUM_SCREEN';
export const CALENDAR_SCREEN = 'CALENDAR_SCREEN';
export const SIGN_UP_SCREEN = 'SIGN_UP_SCREEN';
export const RESET_PASSWORD_ENTER_EMAIL_SCREEN =
  'RESET_PASSWORD_ENTER_EMAIL_SCREEN';
export const RESET_PASSWORD_ENTER_OTP_SCREEN =
  'RESET_PASSWORD_ENTER_OTP_SCREEN';
export const RESET_PASSWORD_ENTER_NEW_PASSWORD_SCREEN =
  'RESET_PASSWORD_ENTER_NEW_PASSWORD_SCREEN';
export const CLASS_PREVIEW_SCREEN = 'CLASS_PREVIEW_SCREEN';
export const CLASS_STACK = 'CLASS_STACK';
export const ARTICLE_SCREEN = 'ARTICLE_SCREEN';
export const ANIMATION_SCREEN = 'ANIMATION_SCREEN';
export const VIDEO_SCREEN = 'VIDEO_SCREEN';
export const QUIZ_SCREEN = 'QUIZ_SCREEN';
export const PRACTICE_ROOM_SCREEN = 'PRACTICE_ROOM_SCREEN';
export const HOT_TOPIC_STACK = 'HOT_TOPIC_STACK';
export const ARTICLE_LIST_SCREEN = 'ARTICLE_LIST_SCREEN';
export const ARTICLE_DETAILS_SCREEN = 'ARTICLE_DETAILS_SCREEN';
