export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const CLASS_SCREEN = 'CLASS_SCREEN';
export const ACCOUNT_SCREEN = 'ACCOUNT_SCREEN';
export const TAB_NAVIGATOR = 'TAB_NAVIGATOR';
export const FORUM_SCREEN = 'FORUM_SCREEN';
export const PHOTO_ALBUM_SCREEN = 'PHOTO_ALBUM_SCREEN';
export const CALENDAR_SCREEN = 'CALENDAR_SCREEN';
export const SIGN_UP_SCREEN = 'SIGN_UP_SCREEN';
export const RESET_PASSWORD_ENTER_EMAIL_SCREEN =
  'RESET_PASSWORD_ENTER_EMAIL_SCREEN';
export const RESET_PASSWORD_ENTER_OTP_SCREEN =
  'RESET_PASSWORD_ENTER_OTP_SCREEN';
export const RESET_PASSWORD_ENTER_NEW_PASSWORD_SCREEN =
  'RESET_PASSWORD_ENTER_NEW_PASSWORD_SCREEN';
export const CLASS_PREVIEW_SCREEN = 'CLASS_PREVIEW_SCREEN';
export const CLASS_STACK = 'CLASS_STACK';
